name: QuickEats Monorepo CI-CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validar Ecosistema Completo
        run: |
          echo "Validando Gateway..."
          cd gateway && npm install && npm run build --if-present
          
          echo "Validando Auth Service..."
          cd ../auth-service && npm install && npx prisma generate && npm run build --if-present
          
          echo "Validando Restaurant Service..."
          cd ../restaurant-service && npm install && npx prisma generate && npm run build --if-present
          
          echo "Validando Order Service..."
          cd ../order-service && npm install && npx prisma generate && npm run build --if-present
          
          echo "Validando Notification Service..."
          cd ../notification-service && npm install && npx prisma generate && npm run build --if-present
          
          echo "Validando Frontend..."
          cd ../frontend && npm install && npm run build --if-present

  deploy-to-staging:
    needs: build-and-validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Codigo para Servidores
        uses: actions/checkout@v4

      - name: Iniciar sesion en Azure Container Registry (ACR)
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Construir y Subir Frontend
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL="https://ca-gateway.braveground-047a1b6e.eastus2.azurecontainerapps.io" -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest ./frontend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

      - name: Construir y Subir Gateway
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/gateway:latest ./gateway
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/gateway:latest

      - name: Construir y Subir Auth Service
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/auth-service:latest ./auth-service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/auth-service:latest

      - name: Construir y Subir Restaurant Service
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/restaurant-service:latest ./restaurant-service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/restaurant-service:latest

      - name: Construir y Subir Order Service
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/order-service:latest ./order-service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/order-service:latest

      - name: Construir y Subir Notification Service
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notification-service:latest ./notification-service
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notification-service:latest